---


#  This is union web site params' file.  The file is in yaml format.  The file
#  should be auto-documented


#  the port where the union web site will run
port: 1999

# the host name.  0.0.0.0 to share the service with everyone on the network.
# localhost for running on localhost without the possibility to share the
# service
host: 0.0.0.0  #localhost



# all the params relative to mongodb
mongo:
    # the url where to get mongodb
    url: localhost:27017

    # the name of the database to use
    database_name: amazon_union
